### ISSUE TITLE
chore: Release v0.0.1 checklist

### ISSUE THREAD

**Issue by lxfontes** [wasmCloud/component-sdk-go#3]
# Repo / Logistics
- [x] License
- [x] CODEOWNERS
- [x] CI Actions ( test, build examples, check format, golangci-lint )
- [ ] Build wasip1 too (?)
- [x] Enable Dependabot
- [ ] Review Repo security settings
- [x] PR Template ( NOTE: configured at org level )
- [x] Update README.md ( include pkg doc link )
- [ ] Reset commit history
- [ ] Block pushes to `main` branch
- [x] DCO ( NOTE: configured at org level )

# Code
- [x] Verify vanity URL works ( `go.wasmcloud.dev/component` )
- [x] Go mod hygiene ( tidy, versions, dependencies )
- [x] Go-doc for all public structs / functions
- [x] HTTP Client example
- [ ] Lattice Linkset example

# Post-Release
- [ ] Update wasmCloud/wasmCloud examples
- [ ] Publish wit archive (?)
- [ ] Land https://github.com/wasmCloud/wasmCloud/issues/3049

**Comment by rvolosatovs** [comment]
> Reset commit history

is there a reason for this?

**Comment by joonas** [comment]
@lxfontes given [`v0.0.1`](https://github.com/wasmCloud/component-sdk-go/releases/tag/v0.0.1) is out, should this be closed out and the remainder of the items filed as follow-up issues as necessary?

**Comment by brooksmtownsend** [comment]
Sorry @lxfontes I moved this on the roadmap and automation closed it, feel free to reopen (I figure it's fine because v0.0.3 is out now?)
